server:
  port: 8099
  forward-headers-strategy: framework
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true
    discovery:
      locator:
        enabled: true

spring.cloud.gateway:
#  default-filters:
#    - name: GlobalFilter
#      args:
#        baseMessage: Spring Cloud Gateway GlobalFilter
#        preLogger: true
#        postLogger: true
  routes:
#    - id: ${spring.application.name}
#      uri: lb://${spring.application.name}
#      predicates:
#        - Path=/openapi/${spring.application.name}
#      filters:
#        - RewritePath=/openapi/${spring.application.name}, /openapi
    - id: openapi
      uri: http://localhost:${server.port}
      predicates:
        - Path=/v3/api-docs/**
      filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    - id: country-service
      uri: lb://address-service
      predicates:
        - Path=/country/**
      filters:
        - RewritePath=/country/(?<path>.*), /$\{path}
    - id: article-service
      uri: lb://article-service
      predicates:
        - Path=/**
      filters:
        - RewritePath=/(?<path>.*), /$\{path}





eureka:
  client:
    serviceURL:
      defaultZone: http://192.168.1.149:8761/eureka

#        .route("country", r->r.path("/country/**").uri(MS_ADDRESS_LABEL)) //static routing
#        .route("state", r->r.path("/state/**").uri(MS_ADDRESS_LABEL)) //dynamic routing
#        .route("city", r->r.path("/city/**").uri(MS_ADDRESS_LABEL))

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
