server:
  port: 8099

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true
    discovery:
      locator:
        enabled: true

eureka:
  client:
    serviceURL:
      defaultZone: http://192.168.1.149:8761/eureka

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
