server:
  port: 8099
  forward-headers-strategy: framework
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true
    discovery:
      locator:
        enabled: true

spring.cloud.gateway:
  routes:
    - id: openapi-versioned
      uri: http://localhost:${server.port}
      predicates:
        - Path=/v3/api-docs/*/v*
      filters:
        - RewritePath=/v3/api-docs/(.*)/(.*), /$1/v3/api-docs/$2

    # route to catch swagger definitions requests and rewrite it to the corresponding url unversioned service
    - id: openapi
      uri: http://localhost:${server.port}
      predicates:
        - Path=/v3/api-docs/**
      filters:
        - RewritePath=/v3/api-docs/(.*), /$1/v3/api-docs
    - id: address-service
      uri: lb://address-service
      #      uri: http://localhost:8084
      predicates:
        - Path=/address/**
      filters:
        - RewritePath=/address/(?<path>.*), /address/v3/api-docs/
    - id: country
      uri: lb://address-service
      predicates:
        - Path=/country/**
    - id: city
      uri: lb://address-service
      predicates:
        - Path=/city/**
    - id: state
      uri: lb://address-service
      predicates:
        - Path=/state/**
    - id: article-service
      uri: lb://article-service
      #      uri: http://localhost:8084
      predicates:
        - Path=/article/**
      filters:
        - RewritePath=/article/(?<path>.*), /article/v3/api-docs/
eureka:
  client:
    serviceURL:
      defaultZone: http://192.168.1.149:8761/eureka

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug
