server:
  port: 8099

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true
    discovery:
      locator:
        enabled: true
      routes:
        - id: address_route
          uri: lb://MS-ADDRESS
          #uri: http://localhost:8084
          predicates:
            - Path=/country/**
            - Path=/city/**
            - Path=/address/**
eureka:
  client:
    serviceURL:
      defaultZone: http://192.168.1.149:8761/eureka
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
